<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Квиз_Логистика_01',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'vd@dobroezzhev.ru',
		'to' => 'vd@dobroezzhev.ru'
	),
	'fields' => array(
		'custom_U3385' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Имя',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U3395' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Сотовый телефон',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U3407' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Сообщение',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U3390' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Выпадающий список',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U3399' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Откуда Китай',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U3416' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Куда Россия',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U3420' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Срок доставки',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U3412' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Емаил',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U4302' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Вес партии',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U4684' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Объем',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U5217' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Тип груза сообщение',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U5236' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Тип груза',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
